baseURL = "https://tasasei.github.io/mysite/"
languageCode = "jp"
title = "tasasei's site"
theme = "ananke"
pygmentsCodefences = true
publishDir = "docs"

[params]
  favicon = ""
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/head.jpg"

